name: Master

on:
  push:
  workflow_dispatch:
  schedule:
    # Run once a month
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk+fx
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew buildJar
      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ChunkyAnimatePlugin
          path: build/libs/ChunkyAnimate.jar
      -name: Upload Standalone Jar
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ChunkyAnimateStandalone
          path: build/libs/ChunkyAnimate-Standalone.jar
